spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003171

server:
  port: 8080

logging:
  file: ${user.home}/logs/100003171/apollo-configservice.log
